# Generated by Django 2.2.13 on 2020-06-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
